"""
Story CSV Builder -- Location Accuracy
=======================================
Reads the result CSVs produced by:
    - decile_install_rate.py   (separate install + decline slices, V1)
    - unified_decile_analysis.py (unified cohort + prob + nearest_type, V2)
And assembles a single narrative CSV (STORY.csv) that reads top-to-
bottom like a report when opened in a spreadsheet.

Invoke AFTER running the pipelines, whenever the story needs updating:
    python unified_decile_analysis.py
    python write_story.py

Extending: add a new section by calling one of the helpers (sec / p /
blank / table_rows) inside build_story(). Sections are numbered and
ordered top-to-bottom.

Run from: system_build/analyses/data/location_accuracy/
"""

import csv
from datetime import datetime
from pathlib import Path

import pandas as pd


HERE = Path(__file__).resolve().parent
INV_DIR = HERE / "investigative"
OUT_PATH = HERE / "STORY.csv"


# ============================================================
# INPUT CSVS (regenerated by the pipelines into investigative/)
# ============================================================
COHORT_UNIFIED    = INV_DIR / "cohort_unified_raw.csv"
DECILE_UNIFIED    = INV_DIR / "decile_unified_summary.csv"
DECILE_PROB       = INV_DIR / "decile_prob_summary.csv"
SUMMARY_TYPE      = INV_DIR / "summary_by_nearest_type.csv"
PROB_X_TYPE       = INV_DIR / "prob_decile_by_nearest_type.csv"
PROB_TYPE_COMP    = INV_DIR / "prob_decile_splitter_composition.csv"


# ============================================================
# FORMATTING HELPERS
# ============================================================
def table_rows(df, num_cols=None, pct_cols=None):
    """OBJECTIVE: Convert a DataFrame to a list-of-lists (header + data)
    with per-column formatting so the story CSV renders cleanly in a
    spreadsheet. pct_cols -> 0.12 -> '12.00%'. num_cols={col: dp}."""
    pct_cols = pct_cols or []
    num_cols = num_cols or {}
    out = [list(df.columns)]
    for _, r in df.iterrows():
        row = []
        for col in df.columns:
            v = r[col]
            if col in pct_cols:
                row.append("" if pd.isna(v) else f"{float(v):.2%}")
            elif col in num_cols:
                dp = num_cols[col]
                row.append("" if pd.isna(v) else f"{float(v):,.{dp}f}")
            elif isinstance(v, float):
                row.append("" if pd.isna(v) else f"{v:,.2f}")
            else:
                row.append(v)
        out.append(row)
    return out


# ============================================================
# STORY ASSEMBLY
# ============================================================
def build_story():
    """OBJECTIVE: Load every result CSV, weave the narrative around
    them, and return the full row buffer. Kept pure -- no I/O here
    except the CSV reads. Caller writes the file."""

    # ---- load inputs ----
    cohort = pd.read_csv(COHORT_UNIFIED)
    non_bdo = cohort[cohort["bdo_lead"] == 0].copy()
    distance_summary = pd.read_csv(DECILE_UNIFIED)
    prob_summary = pd.read_csv(DECILE_PROB)
    type_summary = pd.read_csv(SUMMARY_TYPE)
    prob_x_type = pd.read_csv(PROB_X_TYPE)
    type_comp = pd.read_csv(PROB_TYPE_COMP)

    R = []

    def sec(title):
        R.append([])
        R.append([f"## {title}"])
        R.append([])

    def p(text):
        R.append([text])

    def blank():
        R.append([])

    # ---- HEADER ----
    R.append(["GENIE LOCATION ACCURACY  --  FULL STORY"])
    R.append([f"Last run: {datetime.now():%Y-%m-%d %H:%M:%S}"])
    R.append(["Cohort: Delhi, Dec 2025. Non-BDO filter applied."])
    R.append(["Status: Analysis complete. Final answers in sections 11-14."])
    blank()
    p("OPERATIONAL CONTEXT (anchor for new readers):")
    p("  Allocation runs BEFORE partner decisions. It ranks candidate partners by install")
    p("  likelihood; the top-ranked partner is notified first. Production comparison of")
    p("  signals is therefore UNCONDITIONAL -- the state a new booking arrives in.")
    p("  The 'conditional-accept' slice we compute in section 9 is a DIAGNOSTIC only,")
    p("  not an operational comparison. Details in section 14.")

    # ---- 1. QUESTION ----
    sec("1. THE QUESTION")
    p("Does the partner-to-booking distance at allocation predict installation outcomes,")
    p("and which decline reasons cluster where?")
    blank()
    p("SCOPE: this is a post-Promise-Maker analysis. Every row already passed the 25m")
    p("serviceability gate (booking_location CTE filters to serviceable = TRUE). We are")
    p("evaluating ALLOCATION (GNN ranking of partners for a booking) -- NOT Promise Maker.")
    p("A separate lead-level Promise Maker analysis will follow.")
    blank()
    p("Why it matters: Allocation keys on nearest_distance to rank partners. If the signal")
    p("is confounded with partner tenure (splitter vs active_base) or with decline-reason")
    p("gaming (area -> address_not_clear substitution), every ranking inherits the bias.")

    # ---- 2. COHORT ----
    sec("2. COHORT & FILTERS")
    p("Source: Delhi, Dec 2025 bookings. Query: query_unified_correl.txt.")
    p("Grain: one row per (mobile, partner_id) pair. rn=1 on first decision (ORDER BY added_time ASC).")
    blank()
    p("Decision events considered: INTERESTED, ASSIGNED, DECLINED.")
    p("Exclusion: DECLINED with source='System_Force_Declined_Post_Assigned_72hours' (system auto-decline).")
    blank()
    p("Python-side filter: bdo_lead == 0 (non-BDO bookings only).")
    p("Rationale: BDO bookings are ops-captured -- different journey from self-serve.")
    blank()
    p("Counts:")
    R.append(["raw cohort", len(cohort)])
    R.append(["after non-BDO filter", len(non_bdo)])
    blank()
    p("Decision event mix (non-BDO):")
    evt = non_bdo["decision_event"].astype(str).str.upper().value_counts(dropna=False)
    R.append(["event", "count", "pct"])
    for e, n in evt.items():
        R.append([e, int(n), f"{n / len(non_bdo):.1%}"])

    # ---- 3. GLOSSARY ----
    sec("3. METRICS GLOSSARY")
    p("Helper text: what each ratio/field means.")
    blank()
    R.append(["term", "definition"])
    R.append(["total_obs", "(mobile, partner_id) pairs with a decision in scope"])
    R.append(["pct_installed", "same-partner OTP_VERIFIED after allocation / total_obs"])
    R.append(["pct_area_decline", "DECLINED rows whose reason matches AREA regex / total_obs"])
    R.append(["pct_address_not_clear", "DECLINED rows whose reason matches ADDRESS regex / total_obs"])
    R.append(["separation", "max(metric) - min(metric) across deciles. Headline signal for each slice."])
    R.append(["nearest_distance", "km from partner's nearest active_base OR splitter to booking lat/lng"])
    R.append(["nearest_type", "'active_base' (from prior install) or 'splitter' (onboarding proxy)"])
    R.append(["probability", "GNN-predicted install probability for this (partner, booking) match"])
    R.append(["area regex", "feasibility + spelling variants, coverage/zone/outside, serviceability, network/signal, line/wire/cable/fiber, range/reach, Hindi distance words (dur/door/daira), infra (rfs/pole/jb/olt), 'meters or more away' dropdown"])
    R.append(["address regex", "'understand the address' (English dropdown) | 'पता समझ' (Hindi sibling)"])
    R.append(["BDO lead", "ops-captured booking -- excluded here to focus on self-serve journey"])

    # ---- 4. TIMELINE ----
    sec("4. ANALYSIS TIMELINE")
    p("Chronological steps we took to get here.")
    blank()
    R.append(["step", "what we did"])
    R.append([1, "Distance deciles on install cohort (INTERESTED/ASSIGNED). Install rate: 72.5% -> 22.6%. Distance matters."])
    R.append([2, "Distance deciles on decline cohort. Excluded System_Force_Declined_Post_Assigned_72hours. Built regex for area-related declines."])
    R.append([3, "Sampled 'meters or more away' (2236 rows) and 'Couldn't understand the address' (4962 rows) -- both confirmed system dropdowns, not free-text. Split address-unclear into its own metric."])
    R.append([4, "Unified cohort: INTERESTED + ASSIGNED + DECLINED-non-72h in one table. Switched denominator from total_declines to total_obs (Geoff's Leak B fix)."])
    R.append([5, "Non-BDO filter applied. Cohort dropped 27,303 -> 11,870 (56%)."])
    R.append([6, "Added GNN probability + nearest_type (active_base vs splitter) to the allocation CTE."])
    R.append([7, "Probability decile table: install separation 56.77% -- stronger than raw distance (43.81%)."])
    R.append([8, "Nearest_type groupby: splitter underperforms active_base by ~15pp on install, +6-8pp on each decline bucket."])
    R.append([9, "Prob decile × nearest_type cross-table: GNN partially absorbs splitter signal (composition monotonic 38% -> 12%), but residual 10-17pp mid-decile penalty remains."])

    # ---- 5. DISTANCE DECILE ----
    sec("5. INSTALL / DECLINES BY DISTANCE DECILE (non-BDO)")
    p("Bucket: pd.qcut on nearest_distance. Decile 1 = nearest, decile 10 = farthest.")
    p("Denominator: total_obs (all non-BDO allocations with a decision).")
    blank()
    R.extend(table_rows(
        distance_summary,
        num_cols={"decile": 0, "total_obs": 0, "n_installed": 0, "n_area_decline": 0,
                  "n_address_not_clear": 0, "d_min": 3, "d_max": 3, "d_median": 3},
        pct_cols=["pct_installed", "pct_area_decline", "pct_address_not_clear"],
    ))
    blank()
    p("Separations (D1 - D10 spread, our headline signal):")
    R.append(["metric", "separation"])
    for col in ("pct_installed", "pct_area_decline", "pct_address_not_clear"):
        sep = distance_summary[col].max() - distance_summary[col].min()
        R.append([col, f"{sep:.2%}"])
    blank()
    p("Read: install rate drops ~50% -> ~7%. Monotonic decay.")
    p("Both decline buckets rise monotonically. Area ~6% -> ~26%, address ~10% -> ~29%.")
    p("Decile 10 d_max is a long tail -- likely data hygiene (partner lat/lng errors).")

    # ---- 6. PROB DECILE ----
    sec("6. INSTALL / DECLINES BY PROBABILITY DECILE (non-BDO)")
    p("Bucket: pd.qcut on GNN probability. Decile 1 = lowest predicted prob, decile 10 = highest.")
    p("probability NULL in ~7% of rows -- these drop from this slice but stay in slices 5, 7.")
    blank()
    R.extend(table_rows(
        prob_summary,
        num_cols={"prob_decile": 0, "total_obs": 0, "n_installed": 0, "n_area_decline": 0,
                  "n_address_not_clear": 0, "p_min": 4, "p_max": 4,
                  "p_median": 4, "d_median": 2},
        pct_cols=["pct_installed", "pct_area_decline", "pct_address_not_clear"],
    ))
    blank()
    p("Separations:")
    R.append(["metric", "separation"])
    for col in ("pct_installed", "pct_area_decline", "pct_address_not_clear"):
        sep = prob_summary[col].max() - prob_summary[col].min()
        R.append([col, f"{sep:.2%}"])
    blank()
    p("Read: probability dominates raw distance on every metric.")
    p("At prob_decile 1, ~48% of allocations end in 'couldn't understand address'. When the GNN")
    p("thinks the match is poor, partners dismiss via address_not_clear almost half the time.")
    p("Direct numerical support for the dismissal-leak hypothesis.")

    # ---- 7. NEAREST TYPE GROUPBY ----
    sec("7. NEAREST_TYPE GROUPBY (active_base vs splitter)")
    p("Partners with no prior install have no active_base point -- the system uses 'splitter'")
    p("(a fixed distribution point) as the install-proxy. Splitter is the cold-start signal.")
    blank()
    R.extend(table_rows(
        type_summary,
        num_cols={"total_obs": 0, "n_installed": 0, "n_area_decline": 0,
                  "n_address_not_clear": 0, "d_min": 3, "d_max": 3, "d_median": 3},
        pct_cols=["pct_installed", "pct_area_decline", "pct_address_not_clear"],
    ))
    blank()
    p("Read: splitter share ~30%. Install rate ~22% vs ~37% for active_base (-15pp).")
    p("Both decline buckets ~6pp higher for splitter. Splitter d_median is higher (~25 vs ~18 km) --")
    p("raw gap partly distance-driven. Matched-distance contrast is the cleaner next step.")

    # ---- 8. PROB DECILE × NEAREST_TYPE ----
    sec("8. PROB DECILE × NEAREST_TYPE  --  does GNN already encode type?")
    p("If GNN learned from the splitter edges Maanas fed it, two things should hold:")
    p("  (a) It should route splitters to lower prob deciles (composition shifts).")
    p("  (b) Within a fixed prob decile, active_base and splitter should install at similar rates.")
    blank()
    p("8a. Composition -- % splitter per prob decile:")
    R.extend(table_rows(
        type_comp,
        num_cols={"prob_decile": 0, "total": 0, "splitter": 0, "active_base": 0},
        pct_cols=["pct_splitter"],
    ))
    blank()
    p("Read: monotonic decline 38% -> 12% splitter share. GNN DOES route splitters to low prob. (a) PASSES.")
    blank()
    p("8b. Side-by-side rates per (prob_decile, nearest_type):")
    R.extend(table_rows(
        prob_x_type,
        num_cols={"prob_decile": 0, "total": 0, "n_installed": 0, "n_area": 0, "n_addr": 0,
                  "p_median": 4, "d_median": 2},
        pct_cols=["pct_installed", "pct_area", "pct_addr"],
    ))
    blank()
    p("Read: at every prob decile, splitter installs LESS than active_base. Gap collapses at extremes")
    p("(decile 1: ~3pp, decile 10: ~3pp) but is 10-17pp at mid-prob (deciles 3-6). (b) PARTIAL PASS.")
    blank()
    p("Interpretation (two non-exclusive reads):")
    p("  1. Model-side: GNN has less signal on splitter edges than decision edges -- noisier in the middle.")
    p("  2. Partner-side: splitters face real-world friction (no routing experience, no local infra)")
    p("     that doesn't show up in any graph edge -- genuine meatspace cold-start.")
    p("Matched-distance 2km bins within fixed prob decile would split these.")

    # ---- 9. CONDITIONAL-ACCEPT  --  DIAGNOSTIC SLICE, NOT OPERATIONAL ----
    sec("9. DIAGNOSTIC SLICE  --  conditional-accept (decomposition, NOT operational comparison)")
    p("CAVEAT before reading: this is a diagnostic decomposition, not an operational comparison.")
    p("Allocation runs BEFORE partner decisions (see section 14). This slice tells us WHERE")
    p("probability's unconditional edge over distance comes from -- it does NOT tell us what")
    p("Allocation should use as its ranking signal.")
    blank()
    p("Slice: filter to decision_event IN ('INTERESTED','ASSIGNED'), then install_rate by decile.")
    p("Purpose: separate the partner-willingness leg from the install-physics leg.")
    blank()
    R.append(["cohort", "accepted only", "n=7,675 (64.7% of non-BDO)"])
    blank()
    p("Separation comparison (D1 -> D10):")
    R.append(["slice", "distance", "probability"])
    R.append(["unconditional (all decisions -- production-relevant)", "43.81%", "56.77%"])
    R.append(["conditional-accept (diagnostic only)", "40.15%", "39.95%"])
    blank()
    p("Two reads from this slice:")
    p("  a. Physical ceiling at the tail: at D10 conditional-install is 22.79%. Even accepted")
    p("     bookings fail 3 of 4 times at ~74km. This is Wiom's fiber-reach Shannon limit.")
    p("     Informs: treat 50km+ as a tail refusal zone (action #2 in recommendations).")
    p("  b. Decomposition of prob's advantage: prob carries install-physics signal AND partner-")
    p("     willingness signal. Conditional-accept strips the willingness channel, leaving just")
    p("     physics. Both axes carry similar physics signal (~40% sep). Prob's unconditional")
    p("     57% vs distance's 44% = the ~13pp willingness-channel contribution.")
    blank()
    p("Do NOT read this as 'probability is really just a decline predictor'. The willingness")
    p("channel is a real, valid signal that Allocation needs at inference time -- partners")
    p("haven't declined yet, but the GNN knows from history who usually does. That's the")
    p("information distance can't encode.")
    blank()
    p("Earlier rounds of analysis misread this slice as a critique. That reading was retracted")
    p("in round 6 (see section 14 + timeline).")

    # ---- 10. TENURE-GAP INVESTIGATION ----
    sec("10. TENURE-GAP INVESTIGATION  --  what drives the splitter-vs-active_base install gap?")
    p("Hypotheses tested against partner-level data from t_partner + t_active_base + t_node_splitter_gs:")
    p("  H1 -- Cold-start: gap comes from newer partners who haven't built active_base yet.")
    p("  H2 -- Splitter-share: gap comes from partners who roam-submit lat/lng as splitter points to")
    p("        attract bookings. Gaming-adjacent behavior unseen by the GNN.")
    blank()
    p("10a. Install rate by tenure_bucket x nearest_type (H1 test):")
    R.append(["tenure", "active_base", "splitter", "gap (pp)"])
    R.append(["<=30d", "33.33%", "64.29%", "-31.0  (splitter WINS, small n=54)"])
    R.append(["31-90d", "44.44%", "39.68%", "+4.8"])
    R.append(["91-180d", "37.50%", "18.00%", "+19.5"])
    R.append(["181-365d", "34.68%", "25.76%", "+8.9"])
    R.append(["366-730d", "35.16%", "19.72%", "+15.4"])
    R.append(["730d+", "38.59%", "20.97%", "+17.6"])
    blank()
    p("Read: gap persists (18pp) for 730d+ mature partners. Tenure does NOT explain the gap. H1 REJECTED.")
    blank()
    p("10b. Install rate by prob_decile x partner_splitter_share (H2 test):")
    p("  splitter_share = splitter_count / (splitter_count + active_base_count)  [dedup'd lat/lng]")
    R.append(["prob_decile", "share 0-10%", "share 10-50%", "share 50-90%", "share 90-100%"])
    R.append([3, "24.41%", "13.12%", "7.52%", "4.76%"])
    R.append([4, "35.77%", "20.48%", "19.22%", "5.00%"])
    R.append([5, "39.52%", "24.69%", "29.75%", "33.33%"])
    R.append([6, "41.43%", "36.57%", "35.76%", "n=6"])
    R.append([7, "46.39%", "41.03%", "43.92%", "n=1"])
    R.append([8, "58.03%", "48.53%", "54.94%", "n=0"])
    blank()
    p("Read: at prob_decile 4, partners with <10% splitter share install at 35.77% vs 5.00% for partners")
    p("with >90% splitter share. 31pp gap at the SAME probability. H2 SUPPORTED. Gaming-adjacent partners")
    p("get mid-prob rankings they don't deserve based on actual install performance. GNN does not currently")
    p("discount this. High prob deciles have ~0 high-splitter-share partners -- GNN correctly filters the")
    p("extreme tail, but the middle is where the leak sits.")
    blank()
    p("Note: t_node_splitter_gs already stored as distinct (partner, lat, lng) -- 0 duplicate rows.")
    p("Gaming pattern = many *different* lat/lngs per partner, not repeated pings of one point.")

    # ---- 11. KEY FINDINGS ----
    sec("11. KEY FINDINGS  --  full stack")
    R.append(["#", "finding"])
    R.append([1, "Distance predicts install rate: ~50% -> ~7% across non-BDO deciles. Unconditional separation 44%."])
    R.append([2, "Probability outperforms distance unconditionally (57% sep) but COLLAPSES to match distance when we condition on accept (40% vs 40%). Probability was modeling decline-likelihood, not physical install probability."])
    R.append([3, "At distance D10, conditional install rate is 22.79% (even accepted bookings fail 3 of 4 times). Physical ceiling at the tail."])
    R.append([4, "Address_not_clear is a dismissal channel, not pure parsing failure. 48% at prob_decile 1, 2.5% at decile 10."])
    R.append([5, "The 10-17pp splitter vs active_base install gap is NOT tenure-driven. 730d+ partners show 18pp gap. H1 rejected."])
    R.append([6, "The gap IS partner splitter_share driven. At prob_decile 4: 35.77% install (share<10%) vs 5.00% install (share>90%). 31pp gap at same GNN probability. H2 supported."])
    R.append([7, "Non-BDO is 43.5% of total volume but has SHALLOWER distance gradient -- BDO was driving some of the raw signal."])
    R.append([8, "Decile 10 tail is data hygiene -- isolate as separate population before trusting as a decile."])

    # ---- 12. OPEN QUESTIONS ----
    sec("12. OPEN QUESTIONS & NEXT STEPS")
    p("From Geoff (first-principles review):")
    R.append(["id", "status", "item"])
    R.append(["G1", "RESOLVED", "Conditional-accept at tail -- done. Tail is a physical ceiling (22.79% install even among accepted at D10)."])
    R.append(["G2", "open", "Dropdown-UX check: is 'Address unclear' the default/top option in the partner app? Occam before dismissal."])
    R.append(["G3", "open", "Within-partner contrast across deciles -- holds partner constant while distance varies."])
    R.append(["G4", "open", "Within-geohash contrast across partners -- holds substrate constant while partner varies."])
    blank()
    p("From Donna (systems review):")
    R.append(["id", "status", "item"])
    R.append(["D1", "open", "Time-to-decline by decile × reason -- dismissal is fast, parse-failure has modal lag."])
    R.append(["D2", "open", "Drop partner_id equality in install join -- measure same-booking different-partner recovery (breaks match-level framing, booking-level future)."])
    R.append(["D3", "mostly resolved", "Matched-distance bins active_base vs splitter -- partially addressed by tenure-gap investigation (H2 done)."])
    R.append(["D4", "open", "Rule-layer fix: if an address_not_clear booking later installs via ANY partner, reclassify original dismissal -- breaks the reinforcing dismissal loop."])
    R.append(["D5", "open", "Instrument holding-stock between allocation and decision -- queue depth may drive decline quality."])
    blank()
    p("From tenure-gap investigation:")
    R.append(["id", "status", "item"])
    R.append(["T1", "open", "Splitter gaming type: are splitter points clustered near real address (territory inflation) or geographically scattered (lead harvesting)? Per-partner max_dist_from_centroid + radius percentile."])
    R.append(["T2", "open", "Add splitter_share as a GNN feature (or a post-hoc down-weight at mid-prob). The model is currently calibrated on a signal partners are gaming."])
    R.append(["T3", "open", "18 cohort partners missing from t_partner (0.2%). Low impact but worth understanding -- are they deleted / migrated / wrong key type?"])

    # ---- 13. REVISED READ  --  SYNTHESIS ----
    sec("13. REVISED READ  --  HOW TO LOOK AT THE DATA NOW (Geoff + Donna round 3)")
    p("Both agents independently converged on a re-factoring of how we should think about Allocation.")
    blank()
    p("From Geoff (first-principles):")
    p("  P(install) = P(accept) * P(install | accept)")
    p("  Distance predicts the SECOND term (physics: cable reach, survey fatigue, travel).")
    p("  Probability predicts the PRODUCT but mostly loads on the FIRST term (partner willingness).")
    p("  When you condition on accept, you kill term 1 -- prob and distance both collapse to term 2,")
    p("  which is geometric. The GNN's apparent dominance over distance was compositional. The D10")
    p("  conditional install rate of 22.79% is Wiom's fiber-reach Shannon limit -- no ranking punches through.")
    blank()
    p("From Donna (systems):")
    p("  Splitter submission is a reinforcing 'success to the successful' loop (Meadows #3):")
    p("    more splitters submitted -> wider notification footprint -> more allocations")
    p("    -> occasional installs -> partner perceives gaming as rational -> more splitters")
    p("  No balancing loop exists because splitter points never expire or get validated against installs.")
    p("  The stock being gamed is PERCEIVED SERVICEABILITY.")
    blank()
    p("Convergent inferences:")
    R.append(["#", "inference"])
    R.append([1, "Allocation objective should factorize: (a) accept model = P(accept|notification), (b) conditional-install model = P(install|accept). Rank on the product but inspect each leg."])
    R.append([2, "The current GNN 'probability' is a decline-likelihood predictor wearing fit-predictor clothes. Distance is an orthogonal geometric signal governing the physics leg."])
    R.append([3, "Adding splitter_share as a GNN feature is a band-aid. Gamers will mutate the pattern (e.g. keep share below threshold via multiple partner IDs). Durable fix: validate splitter points against install outcomes -- turn unbounded stock into one with a decay flow."])
    R.append([4, "The training label itself is contaminated -- gamers generate splitter points AND fail to install. Every retrain re-inherits the pathology. Real fix is UPSTREAM, before nearest-distance computation."])
    R.append([5, "Geoff's architectural question: does Allocation need a REFUSAL PRIMITIVE? A way to return a booking to Promise Maker saying 'no partner I rank can clear the physics bar.' Today every booking routes; losses absorb as declines."])
    R.append([6, "D10 is a hard physical ceiling (~23% conditional install). Any intervention at D10 is about routing away, not improving. Needs to be disambiguated from data-hygiene tail (448km+)."])
    blank()
    p("Next-step leverage ranking (merged):")
    R.append(["rank", "item", "why"])
    R.append([1, "Time-to-decline by decile x reason (D1)", "Separates willingness from physics -- the whole ballgame post-conditional-accept."])
    R.append([2, "Within-partner across deciles (G3)", "Holds partner constant. Cleanest test of distance-as-physics-ceiling."])
    R.append([3, "Reclassify address_not_clear on ANY-partner install (D4)", "Turns self-reported dismissal into outcome-validated signal. Breaks the gaming reward."])
    R.append([4, "Instrumentation for gaming detection (Donna new)", "Watch slopes of submission-rate vs install-conversion-rate per partner. Gaming signature shows in derivatives."])
    R.append([5, "Different-partner recovery (D2)", "Required for D4. Breaks match-level framing, goes booking-level."])
    R.append([6, "Within-geohash across partners (G4)", "Holds substrate constant. Confirms gaming is partner-side."])
    R.append([7, "Holding-stock queue depth (D5)", "Medium leverage. Explains latency-driven declines."])
    R.append([8, "Dropdown UX check (G2)", "Small. Occam before dismissal."])

    # ---- 14. FINAL READ -- distance vs probability, across outcomes ----
    sec("14. FINAL READ  --  distance vs GNN probability for Allocation ranking")
    p("Operational context: Allocation runs BEFORE partner decisions -- it ranks candidate")
    p("partners by install likelihood, and the top-ranked partner is notified first. The")
    p("relevant comparison is therefore UNCONDITIONAL -- on the data a new booking actually")
    p("arrives with (no accept/decline signal yet).")
    blank()
    p("Unconditional separation matrix (non-BDO, D1 -> D10 spread):")
    R.append(["category", "distance sep", "GNN prob sep", "winner"])
    R.append(["Install rate", "44%", "57%", "Prob by 13pp"])
    R.append(["Area decline", "20%", "23%", "Prob slightly"])
    R.append(["Address not clear", "19%", "45%", "Prob by 26pp"])
    blank()
    p("Concentration in worst 3 deciles (the decision-utility metric for top-k notification):")
    R.append(["signal", "% area-declines in worst-3 deciles", "interpretation"])
    R.append(["GNN probability (D1+D2+D3, lowest)", "59.3%", "Drop bottom 30% of volume, avoid 59% of area declines"])
    R.append(["Distance (D8+D9+D10, farthest)", "47.9%", "Drop bottom 30% of volume, avoid 48% of area declines"])
    p("GNN is 11pp more concentrated on bad outcomes. Concentration matters more than")
    p("separation for a notify-top-k decision.")
    blank()
    p("Splitter composition (does the signal isolate gaming?):")
    R.append(["rank axis", "%splitter at worst decile", "%splitter at best decile", "behavior"])
    R.append(["GNN probability", "38.33% (D1 low prob)", "12.17% (D10 high prob)", "Monotonic -- GNN routes splitters to low prob"])
    R.append(["Distance", "11.61% (D1 near)", "peak 41.18% at D7 (~29km)", "Scattered -- distance does NOT isolate splitters"])
    blank()
    p("Distance is a GAMEABLE axis: partners submit their own splitter lat/lngs, which")
    p("directly affect the nearest_distance they see. GNN integrates DECLINE HISTORY that")
    p("gamers cannot fake, creating an active balancing loop on gaming behavior.")
    blank()
    p("Why GNN wins: it learns from decline signals, distance doesn't.")
    p("  A distance-based approach is a fixed geometric cut -- it cannot adapt to partner")
    p("  behavior. It does not price decline signals partners send. A partner who declines")
    p("  80% of allocations looks identical to one who installs 80%, if they're at the same")
    p("  distance. The GNN integrates both install and decline edge types (per Maanas's")
    p("  design), weighted geographically and temporally. The GNN's advantage IS the")
    p("  decline-signal channel. Any signal that doesn't learn from declines gives this up.")
    blank()
    p("Diagnostic slice -- conditional-accept (NOT production-relevant):")
    p("  When we filter to decision_event IN ('INTERESTED','ASSIGNED'), the install-rate")
    p("  separations become: distance 40%, probability 40%. They tie. But this is not what")
    p("  Allocation sees at inference time -- Allocation ranks BEFORE any decision is known.")
    p("  The conditional-accept collapse is just the decline signal being removed from the")
    p("  data, which is precisely what GNN is designed to price. Earlier rounds of analysis")
    p("  (and two agent rounds) over-read this as a critique. Retracted.")
    blank()
    p("Shape of decline curves on distance (independent observation):")
    R.append(["category", "shape on distance"])
    R.append(["Area-decline", "Step function -- flat D1-D5 (~7-9%), step up D6 (~10%), big jump D10 (+9pp)"])
    R.append(["Address-not-clear", "Smooth monotonic rise, ~3pp per decile, 9.8% -> 28.5%"])
    p("The address-not-clear monotonic rise IS the dismissal-leak signature -- partners")
    p("farther out use 'address unclear' as a polite decline regardless of actual address")
    p("clarity. If it were pure parsing failure, the curve would be flat on distance.")

    # ---- 15. GNN CONTEXT -- SIDE NOTE ----
    sec("15. GNN CONTEXT  --  side note (parked, not load-bearing)")
    p("This analysis was NOT about GNN architecture. The data answers above stand on their")
    p("own. This section is context for future GNN work only.")
    blank()
    p("Design intent (per Maanas): for every target booking, build a graph that looks at")
    p("historical install and decline decisions by a partner, across partners, along with")
    p("splitter data. Decisions + splitters become edge types, geographically + temporally")
    p("separated. The GNN then predicts whether a target (booking, partner) match will install,")
    p("based on how the partner has behaved across actions (install or decline) in space and time.")
    blank()
    p("One detail worth flagging for future GNN work, surfaced during analysis:")
    p("  - create_gnn.py computes a precomputed attention bias per edge:")
    p("      attention = exp(-time) * 1/(1+dist) * (1 - DECLINED) * (1 + INSTALLED)")
    p("    and stores it as the last column of edge_attr.")
    p("  - The GATConv instances are initialized WITHOUT edge_dim.")
    p("  - In PyTorch Geometric, edge_attr is consumed by GATConv only when edge_dim is set")
    p("    at init (which builds lin_edge). Without edge_dim, edge_attr is silently dropped")
    p("    (older PyG) or raises (newer PyG).")
    p("  - Likely implication: the precomputed attention formula is ORPHAN at runtime --")
    p("    computed and stored but not consumed. Message passing uses GATConv's own learned")
    p("    attention over node features + topology. Both install and decline edge types")
    p("    contribute first-class messages, exactly as intended.")
    p("  - If confirmed at execution: either the HTML doc's attention-interaction claim")
    p("    needs revision, or the code should pass edge_dim=1 to activate the precomputed bias.")
    blank()
    p("Earlier rounds of Geoff + Donna review (round 4) built an 'architectural critique'")
    p("(decline-complement, survivorship bias, three structural fixes) on the documented")
    p("attention formula. That critique was retracted in round 5 when the code was read.")
    p("Logged here for completeness; not load-bearing on this analysis.")

    return R


def main():
    """OBJECTIVE: Assemble the story CSV and write it to disk."""
    rows = build_story()
    with open(OUT_PATH, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f, quoting=csv.QUOTE_MINIMAL)
        for row in rows:
            writer.writerow(row)
    print(f"SAVED: {OUT_PATH.name}  ({len(rows)} rows)")


if __name__ == "__main__":
    main()
